import type { Metadata } from 'next';
import { Itim } from 'next/font/google';
import { Toaster } from '~/components/ui/toaster';

const itim = Itim({ subsets: ['vietnamese'], weight: '400' });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

interface RootLayoutProps {
    children: React.ReactNode;
    params: {
        locale: string;
    };
}

export default async function RootLayout({ children, params: { locale } }: Readonly<RootLayoutProps>) {
    return (
        <html lang={locale} suppressHydrationWarning>
            <body className={itim.className}>
                {children}
                <Toaster />
            </body>
        </html>
    );
}
