import type { Metadata } from 'next';
import { Itim } from 'next/font/google';
import Providers from './providers';

const itim = Itim({ subsets: ['vietnamese'], weight: '400' });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en' suppressHydrationWarning>
            <link href='/favicon.ico' rel='icon' />
            <body className={itim.className}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
